# https://taskfile.dev

version: "3"

tasks:
  ci:
    cmds:
      - task: deps
      - task: fmt
      - task: build
      - task: lint
      - task: test

  deps:
    desc: Install all dependencies for the project
    cmd: go mod download

  run:
    cmds:
      - task: build
      - task: exec

  build:
    cmd: go build -o dist/authkeysync ./cmd

  exec:
    cmd: ./dist/authkeysync

  fmt:
    cmds:
      - go fmt ./...
      - dprint fmt

  lint:
    cmds:
      - golangci-lint run
      - dprint check

  test:
    cmds:
      - go test -v ./...
