package e2e

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestBasicSync verifies that authkeysync can fetch keys from a single source
// and write them correctly to the authorized_keys file.
func TestBasicSync(t *testing.T) {
	_ = newTestCase(t, testUser1)

	// Create config
	configPath := createConfig(t, "basic_sync", `
policy:
  backup_enabled: false
  preserve_local_keys: false

users:
  - username: `+testUser1+`
    sources:
      - url: ${MOCK_SERVER_URL}/users/alice.keys
`)

	// Execute
	output, exitCode := runAuthKeySync(t, "--config", configPath)
	t.Logf("Output: %s", output)

	// Verify exit code
	assert.Equal(t, 0, exitCode, "authkeysync should exit with code 0")

	// Verify file exists and has correct properties
	authKeysPath := getAuthKeysPath(t, testUser1)
	assertFileExists(t, authKeysPath, "authorized_keys file should exist")

	// Check permissions
	perms := getFilePermissions(t, authKeysPath)
	assert.Equal(t, "600", perms, "authorized_keys should have 600 permissions")

	// Check ownership
	owner := getFileOwner(t, authKeysPath)
	assert.Equal(t, testUser1, owner, "authorized_keys should be owned by %s", testUser1)

	// Check content
	content := readAuthKeys(t, testUser1)
	assert.Contains(t, content, "alice@laptop", "Should contain alice's ed25519 key")
	assert.Contains(t, content, "alice@workstation", "Should contain alice's RSA key")
	assert.Contains(t, content, "Generated by AuthKeySync", "Should contain AuthKeySync header")
	assert.Contains(t, content, "# Source:", "Should contain source URL comment")

	// Verify key count
	keyCount := countKeys(t, authKeysPath)
	require.Equal(t, 2, keyCount, "Should have exactly 2 keys")
}
